// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/rating/rating.proto

package rating

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRatingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RestaurantId   int32                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	RestaurantName string                 `protobuf:"bytes,3,opt,name=restaurant_name,json=restaurantName,proto3" json:"restaurant_name,omitempty"`
	Stars          float64                `protobuf:"fixed64,4,opt,name=stars,proto3" json:"stars,omitempty"`
	Comment        string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitRatingRequest) Reset() {
	*x = SubmitRatingRequest{}
	mi := &file_proto_rating_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRatingRequest) ProtoMessage() {}

func (x *SubmitRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRatingRequest.ProtoReflect.Descriptor instead.
func (*SubmitRatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_rating_rating_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRatingRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitRatingRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *SubmitRatingRequest) GetRestaurantName() string {
	if x != nil {
		return x.RestaurantName
	}
	return ""
}

func (x *SubmitRatingRequest) GetStars() float64 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *SubmitRatingRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SubmitRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRatingResponse) Reset() {
	*x = SubmitRatingResponse{}
	mi := &file_proto_rating_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRatingResponse) ProtoMessage() {}

func (x *SubmitRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRatingResponse.ProtoReflect.Descriptor instead.
func (*SubmitRatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_rating_rating_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitRatingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestaurantIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantIDRequest) Reset() {
	*x = RestaurantIDRequest{}
	mi := &file_proto_rating_rating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantIDRequest) ProtoMessage() {}

func (x *RestaurantIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_rating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantIDRequest.ProtoReflect.Descriptor instead.
func (*RestaurantIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_rating_rating_proto_rawDescGZIP(), []int{2}
}

func (x *RestaurantIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RatingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RestaurantId  uint32                 `protobuf:"varint,3,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Stars         float64                `protobuf:"fixed64,4,opt,name=stars,proto3" json:"stars,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingMessage) Reset() {
	*x = RatingMessage{}
	mi := &file_proto_rating_rating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingMessage) ProtoMessage() {}

func (x *RatingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_rating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingMessage.ProtoReflect.Descriptor instead.
func (*RatingMessage) Descriptor() ([]byte, []int) {
	return file_proto_rating_rating_proto_rawDescGZIP(), []int{3}
}

func (x *RatingMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RatingMessage) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RatingMessage) GetRestaurantId() uint32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *RatingMessage) GetStars() float64 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *RatingMessage) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RatingMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RatingMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RatingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratings       []*RatingMessage       `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingsResponse) Reset() {
	*x = RatingsResponse{}
	mi := &file_proto_rating_rating_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingsResponse) ProtoMessage() {}

func (x *RatingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_rating_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingsResponse.ProtoReflect.Descriptor instead.
func (*RatingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rating_rating_proto_rawDescGZIP(), []int{4}
}

func (x *RatingsResponse) GetRatings() []*RatingMessage {
	if x != nil {
		return x.Ratings
	}
	return nil
}

var File_proto_rating_rating_proto protoreflect.FileDescriptor

const file_proto_rating_rating_proto_rawDesc = "" +
	"\n" +
	"\x19proto/rating/rating.proto\x12\x06rating\"\xac\x01\n" +
	"\x13SubmitRatingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x05R\frestaurantId\x12'\n" +
	"\x0frestaurant_name\x18\x03 \x01(\tR\x0erestaurantName\x12\x14\n" +
	"\x05stars\x18\x04 \x01(\x01R\x05stars\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\"0\n" +
	"\x14SubmitRatingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x13RestaurantIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xc8\x01\n" +
	"\rRatingMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12#\n" +
	"\rrestaurant_id\x18\x03 \x01(\rR\frestaurantId\x12\x14\n" +
	"\x05stars\x18\x04 \x01(\x01R\x05stars\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\"B\n" +
	"\x0fRatingsResponse\x12/\n" +
	"\aratings\x18\x01 \x03(\v2\x15.rating.RatingMessageR\aratings2\xac\x01\n" +
	"\rRatingService\x12I\n" +
	"\fSubmitRating\x12\x1b.rating.SubmitRatingRequest\x1a\x1c.rating.SubmitRatingResponse\x12P\n" +
	"\x18GetRatingsByRestaurantID\x12\x1b.rating.RestaurantIDRequest\x1a\x17.rating.RatingsResponseB\x1fZ\x1dfoodRatingSystem/proto/ratingb\x06proto3"

var (
	file_proto_rating_rating_proto_rawDescOnce sync.Once
	file_proto_rating_rating_proto_rawDescData []byte
)

func file_proto_rating_rating_proto_rawDescGZIP() []byte {
	file_proto_rating_rating_proto_rawDescOnce.Do(func() {
		file_proto_rating_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rating_rating_proto_rawDesc), len(file_proto_rating_rating_proto_rawDesc)))
	})
	return file_proto_rating_rating_proto_rawDescData
}

var file_proto_rating_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_rating_rating_proto_goTypes = []any{
	(*SubmitRatingRequest)(nil),  // 0: rating.SubmitRatingRequest
	(*SubmitRatingResponse)(nil), // 1: rating.SubmitRatingResponse
	(*RestaurantIDRequest)(nil),  // 2: rating.RestaurantIDRequest
	(*RatingMessage)(nil),        // 3: rating.RatingMessage
	(*RatingsResponse)(nil),      // 4: rating.RatingsResponse
}
var file_proto_rating_rating_proto_depIdxs = []int32{
	3, // 0: rating.RatingsResponse.ratings:type_name -> rating.RatingMessage
	0, // 1: rating.RatingService.SubmitRating:input_type -> rating.SubmitRatingRequest
	2, // 2: rating.RatingService.GetRatingsByRestaurantID:input_type -> rating.RestaurantIDRequest
	1, // 3: rating.RatingService.SubmitRating:output_type -> rating.SubmitRatingResponse
	4, // 4: rating.RatingService.GetRatingsByRestaurantID:output_type -> rating.RatingsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rating_rating_proto_init() }
func file_proto_rating_rating_proto_init() {
	if File_proto_rating_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rating_rating_proto_rawDesc), len(file_proto_rating_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rating_rating_proto_goTypes,
		DependencyIndexes: file_proto_rating_rating_proto_depIdxs,
		MessageInfos:      file_proto_rating_rating_proto_msgTypes,
	}.Build()
	File_proto_rating_rating_proto = out.File
	file_proto_rating_rating_proto_goTypes = nil
	file_proto_rating_rating_proto_depIdxs = nil
}
