// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/restaurant/restaurant.proto

package restaurant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AvgScore      float64                `protobuf:"fixed64,5,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,7,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantMessage) Reset() {
	*x = RestaurantMessage{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantMessage) ProtoMessage() {}

func (x *RestaurantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantMessage.ProtoReflect.Descriptor instead.
func (*RestaurantMessage) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RestaurantMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantMessage) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RestaurantMessage) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RestaurantMessage) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *RestaurantMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RestaurantMessage) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type NearbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyRequest) Reset() {
	*x = NearbyRequest{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyRequest) ProtoMessage() {}

func (x *NearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyRequest.ProtoReflect.Descriptor instead.
func (*NearbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NearbyRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type RestaurantWithDistance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AvgScore      float64                `protobuf:"fixed64,5,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,7,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	Distance      float64                `protobuf:"fixed64,8,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantWithDistance) Reset() {
	*x = RestaurantWithDistance{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantWithDistance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantWithDistance) ProtoMessage() {}

func (x *RestaurantWithDistance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantWithDistance.ProtoReflect.Descriptor instead.
func (*RestaurantWithDistance) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *RestaurantWithDistance) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RestaurantWithDistance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantWithDistance) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RestaurantWithDistance) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RestaurantWithDistance) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *RestaurantWithDistance) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RestaurantWithDistance) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *RestaurantWithDistance) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type NearbyResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Restaurants   []*RestaurantWithDistance `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyResponse) Reset() {
	*x = NearbyResponse{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyResponse) ProtoMessage() {}

func (x *NearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyResponse.ProtoReflect.Descriptor instead.
func (*NearbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *NearbyResponse) GetRestaurants() []*RestaurantWithDistance {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RecommendRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type RestaurantWithScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AvgScore      float64                `protobuf:"fixed64,5,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,7,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	Distance      float64                `protobuf:"fixed64,8,opt,name=distance,proto3" json:"distance,omitempty"`
	FinalScore    float64                `protobuf:"fixed64,9,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantWithScore) Reset() {
	*x = RestaurantWithScore{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantWithScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantWithScore) ProtoMessage() {}

func (x *RestaurantWithScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantWithScore.ProtoReflect.Descriptor instead.
func (*RestaurantWithScore) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *RestaurantWithScore) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RestaurantWithScore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantWithScore) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RestaurantWithScore) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RestaurantWithScore) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *RestaurantWithScore) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RestaurantWithScore) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *RestaurantWithScore) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *RestaurantWithScore) GetFinalScore() float64 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

type RecommendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*RestaurantWithScore `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *RecommendResponse) GetRestaurants() []*RestaurantWithScore {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Sort          string                 `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	HasLocation   bool                   `protobuf:"varint,5,opt,name=has_location,json=hasLocation,proto3" json:"has_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *SearchRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *SearchRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *SearchRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SearchRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *SearchRequest) GetHasLocation() bool {
	if x != nil {
		return x.HasLocation
	}
	return false
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*RestaurantWithScore `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResponse) GetRestaurants() []*RestaurantWithScore {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type RestaurantIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantIDRequest) Reset() {
	*x = RestaurantIDRequest{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantIDRequest) ProtoMessage() {}

func (x *RestaurantIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantIDRequest.ProtoReflect.Descriptor instead.
func (*RestaurantIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *RestaurantIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RestaurantDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AvgScore      float64                `protobuf:"fixed64,5,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,7,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantDetailResponse) Reset() {
	*x = RestaurantDetailResponse{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantDetailResponse) ProtoMessage() {}

func (x *RestaurantDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantDetailResponse.ProtoReflect.Descriptor instead.
func (*RestaurantDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{10}
}

func (x *RestaurantDetailResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RestaurantDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantDetailResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RestaurantDetailResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RestaurantDetailResponse) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *RestaurantDetailResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RestaurantDetailResponse) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type RatingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RestaurantId  uint32                 `protobuf:"varint,3,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Stars         float64                `protobuf:"fixed64,4,opt,name=stars,proto3" json:"stars,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingMessage) Reset() {
	*x = RatingMessage{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingMessage) ProtoMessage() {}

func (x *RatingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingMessage.ProtoReflect.Descriptor instead.
func (*RatingMessage) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{11}
}

func (x *RatingMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RatingMessage) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RatingMessage) GetRestaurantId() uint32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *RatingMessage) GetStars() float64 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *RatingMessage) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RatingMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RatingMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RestaurantRatingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratings       []*RatingMessage       `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantRatingsResponse) Reset() {
	*x = RestaurantRatingsResponse{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantRatingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantRatingsResponse) ProtoMessage() {}

func (x *RestaurantRatingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantRatingsResponse.ProtoReflect.Descriptor instead.
func (*RestaurantRatingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{12}
}

func (x *RestaurantRatingsResponse) GetRatings() []*RatingMessage {
	if x != nil {
		return x.Ratings
	}
	return nil
}

type CreateRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantRequest) Reset() {
	*x = CreateRestaurantRequest{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRequest) ProtoMessage() {}

func (x *CreateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRestaurantRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateRestaurantRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateRestaurantRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	AvgScore      float64                `protobuf:"fixed64,5,opt,name=avg_score,json=avgScore,proto3" json:"avg_score,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,7,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantResponse) Reset() {
	*x = CreateRestaurantResponse{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantResponse) ProtoMessage() {}

func (x *CreateRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantResponse.ProtoReflect.Descriptor instead.
func (*CreateRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRestaurantResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateRestaurantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRestaurantResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateRestaurantResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateRestaurantResponse) GetAvgScore() float64 {
	if x != nil {
		return x.AvgScore
	}
	return 0
}

func (x *CreateRestaurantResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateRestaurantResponse) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

type InvalidateCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheRequest) Reset() {
	*x = InvalidateCacheRequest{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheRequest) ProtoMessage() {}

func (x *InvalidateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheRequest.ProtoReflect.Descriptor instead.
func (*InvalidateCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{15}
}

func (x *InvalidateCacheRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type InvalidateCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateCacheResponse) Reset() {
	*x = InvalidateCacheResponse{}
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateCacheResponse) ProtoMessage() {}

func (x *InvalidateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateCacheResponse.ProtoReflect.Descriptor instead.
func (*InvalidateCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_proto_rawDescGZIP(), []int{16}
}

func (x *InvalidateCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_restaurant_restaurant_proto protoreflect.FileDescriptor

const file_proto_restaurant_restaurant_proto_rawDesc = "" +
	"\n" +
	"!proto/restaurant/restaurant.proto\x12\n" +
	"restaurant\"\xcd\x01\n" +
	"\x11RestaurantMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tavg_score\x18\x05 \x01(\x01R\bavgScore\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12!\n" +
	"\freview_count\x18\a \x01(\x05R\vreviewCount\"3\n" +
	"\rNearbyRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\xee\x01\n" +
	"\x16RestaurantWithDistance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tavg_score\x18\x05 \x01(\x01R\bavgScore\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12!\n" +
	"\freview_count\x18\a \x01(\x05R\vreviewCount\x12\x1a\n" +
	"\bdistance\x18\b \x01(\x01R\bdistance\"V\n" +
	"\x0eNearbyResponse\x12D\n" +
	"\vrestaurants\x18\x01 \x03(\v2\".restaurant.RestaurantWithDistanceR\vrestaurants\"6\n" +
	"\x10RecommendRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\"\x8c\x02\n" +
	"\x13RestaurantWithScore\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tavg_score\x18\x05 \x01(\x01R\bavgScore\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12!\n" +
	"\freview_count\x18\a \x01(\x05R\vreviewCount\x12\x1a\n" +
	"\bdistance\x18\b \x01(\x01R\bdistance\x12\x1f\n" +
	"\vfinal_score\x18\t \x01(\x01R\n" +
	"finalScore\"V\n" +
	"\x11RecommendResponse\x12A\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x1f.restaurant.RestaurantWithScoreR\vrestaurants\"\x82\x01\n" +
	"\rSearchRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\tR\x04sort\x12!\n" +
	"\fhas_location\x18\x05 \x01(\bR\vhasLocation\"S\n" +
	"\x0eSearchResponse\x12A\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x1f.restaurant.RestaurantWithScoreR\vrestaurants\"%\n" +
	"\x13RestaurantIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xd4\x01\n" +
	"\x18RestaurantDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tavg_score\x18\x05 \x01(\x01R\bavgScore\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12!\n" +
	"\freview_count\x18\a \x01(\x05R\vreviewCount\"\xc8\x01\n" +
	"\rRatingMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12#\n" +
	"\rrestaurant_id\x18\x03 \x01(\rR\frestaurantId\x12\x14\n" +
	"\x05stars\x18\x04 \x01(\x01R\x05stars\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\"P\n" +
	"\x19RestaurantRatingsResponse\x123\n" +
	"\aratings\x18\x01 \x03(\v2\x19.restaurant.RatingMessageR\aratings\"\x83\x01\n" +
	"\x17CreateRestaurantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\xd4\x01\n" +
	"\x18CreateRestaurantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tavg_score\x18\x05 \x01(\x01R\bavgScore\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12!\n" +
	"\freview_count\x18\a \x01(\x05R\vreviewCount\"=\n" +
	"\x16InvalidateCacheRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\"3\n" +
	"\x17InvalidateCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfe\x04\n" +
	"\x11RestaurantService\x12M\n" +
	"\x14GetNearbyRestaurants\x12\x19.restaurant.NearbyRequest\x1a\x1a.restaurant.NearbyResponse\x12X\n" +
	"\x19GetRecommendedRestaurants\x12\x1c.restaurant.RecommendRequest\x1a\x1d.restaurant.RecommendResponse\x12G\n" +
	"\x0eGetRestaurants\x12\x19.restaurant.SearchRequest\x1a\x1a.restaurant.SearchResponse\x12\\\n" +
	"\x13GetRestaurantDetail\x12\x1f.restaurant.RestaurantIDRequest\x1a$.restaurant.RestaurantDetailResponse\x12^\n" +
	"\x14GetRestaurantRatings\x12\x1f.restaurant.RestaurantIDRequest\x1a%.restaurant.RestaurantRatingsResponse\x12]\n" +
	"\x10CreateRestaurant\x12#.restaurant.CreateRestaurantRequest\x1a$.restaurant.CreateRestaurantResponse\x12Z\n" +
	"\x0fInvalidateCache\x12\".restaurant.InvalidateCacheRequest\x1a#.restaurant.InvalidateCacheResponseB#Z!foodRatingSystem/proto/restaurantb\x06proto3"

var (
	file_proto_restaurant_restaurant_proto_rawDescOnce sync.Once
	file_proto_restaurant_restaurant_proto_rawDescData []byte
)

func file_proto_restaurant_restaurant_proto_rawDescGZIP() []byte {
	file_proto_restaurant_restaurant_proto_rawDescOnce.Do(func() {
		file_proto_restaurant_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_restaurant_restaurant_proto_rawDesc), len(file_proto_restaurant_restaurant_proto_rawDesc)))
	})
	return file_proto_restaurant_restaurant_proto_rawDescData
}

var file_proto_restaurant_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_restaurant_restaurant_proto_goTypes = []any{
	(*RestaurantMessage)(nil),         // 0: restaurant.RestaurantMessage
	(*NearbyRequest)(nil),             // 1: restaurant.NearbyRequest
	(*RestaurantWithDistance)(nil),    // 2: restaurant.RestaurantWithDistance
	(*NearbyResponse)(nil),            // 3: restaurant.NearbyResponse
	(*RecommendRequest)(nil),          // 4: restaurant.RecommendRequest
	(*RestaurantWithScore)(nil),       // 5: restaurant.RestaurantWithScore
	(*RecommendResponse)(nil),         // 6: restaurant.RecommendResponse
	(*SearchRequest)(nil),             // 7: restaurant.SearchRequest
	(*SearchResponse)(nil),            // 8: restaurant.SearchResponse
	(*RestaurantIDRequest)(nil),       // 9: restaurant.RestaurantIDRequest
	(*RestaurantDetailResponse)(nil),  // 10: restaurant.RestaurantDetailResponse
	(*RatingMessage)(nil),             // 11: restaurant.RatingMessage
	(*RestaurantRatingsResponse)(nil), // 12: restaurant.RestaurantRatingsResponse
	(*CreateRestaurantRequest)(nil),   // 13: restaurant.CreateRestaurantRequest
	(*CreateRestaurantResponse)(nil),  // 14: restaurant.CreateRestaurantResponse
	(*InvalidateCacheRequest)(nil),    // 15: restaurant.InvalidateCacheRequest
	(*InvalidateCacheResponse)(nil),   // 16: restaurant.InvalidateCacheResponse
}
var file_proto_restaurant_restaurant_proto_depIdxs = []int32{
	2,  // 0: restaurant.NearbyResponse.restaurants:type_name -> restaurant.RestaurantWithDistance
	5,  // 1: restaurant.RecommendResponse.restaurants:type_name -> restaurant.RestaurantWithScore
	5,  // 2: restaurant.SearchResponse.restaurants:type_name -> restaurant.RestaurantWithScore
	11, // 3: restaurant.RestaurantRatingsResponse.ratings:type_name -> restaurant.RatingMessage
	1,  // 4: restaurant.RestaurantService.GetNearbyRestaurants:input_type -> restaurant.NearbyRequest
	4,  // 5: restaurant.RestaurantService.GetRecommendedRestaurants:input_type -> restaurant.RecommendRequest
	7,  // 6: restaurant.RestaurantService.GetRestaurants:input_type -> restaurant.SearchRequest
	9,  // 7: restaurant.RestaurantService.GetRestaurantDetail:input_type -> restaurant.RestaurantIDRequest
	9,  // 8: restaurant.RestaurantService.GetRestaurantRatings:input_type -> restaurant.RestaurantIDRequest
	13, // 9: restaurant.RestaurantService.CreateRestaurant:input_type -> restaurant.CreateRestaurantRequest
	15, // 10: restaurant.RestaurantService.InvalidateCache:input_type -> restaurant.InvalidateCacheRequest
	3,  // 11: restaurant.RestaurantService.GetNearbyRestaurants:output_type -> restaurant.NearbyResponse
	6,  // 12: restaurant.RestaurantService.GetRecommendedRestaurants:output_type -> restaurant.RecommendResponse
	8,  // 13: restaurant.RestaurantService.GetRestaurants:output_type -> restaurant.SearchResponse
	10, // 14: restaurant.RestaurantService.GetRestaurantDetail:output_type -> restaurant.RestaurantDetailResponse
	12, // 15: restaurant.RestaurantService.GetRestaurantRatings:output_type -> restaurant.RestaurantRatingsResponse
	14, // 16: restaurant.RestaurantService.CreateRestaurant:output_type -> restaurant.CreateRestaurantResponse
	16, // 17: restaurant.RestaurantService.InvalidateCache:output_type -> restaurant.InvalidateCacheResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_restaurant_restaurant_proto_init() }
func file_proto_restaurant_restaurant_proto_init() {
	if File_proto_restaurant_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_restaurant_restaurant_proto_rawDesc), len(file_proto_restaurant_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_restaurant_restaurant_proto_goTypes,
		DependencyIndexes: file_proto_restaurant_restaurant_proto_depIdxs,
		MessageInfos:      file_proto_restaurant_restaurant_proto_msgTypes,
	}.Build()
	File_proto_restaurant_restaurant_proto = out.File
	file_proto_restaurant_restaurant_proto_goTypes = nil
	file_proto_restaurant_restaurant_proto_depIdxs = nil
}
